apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-handler-3454
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-handler-3454
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
